defaults:
  - robomimic_state
  - _self_
_target_: ht_regression.data.robomimic.RobomimicImageDataset
camera_keys: [agentview_image, robot0_eye_in_hand_image]
obs_keys: [robot0_eef_pos, robot0_eef_quat, robot0_gripper_qpos]
cache_dir: null
